### ISSUE TITLE
Base off of base-x

### ISSUE THREAD

**Issue by sublimator** [cryptocoinjs/bs58#12]
Pulling the discussion from here:   https://github.com/dcousens/base-x/issues/6

**Comment by sublimator** [comment]
No bites :) ?

**Comment by dcousens** [comment]
I'll PR it up when I can :)

**Comment by sublimator** [comment]
:)

**Comment by jprichardson** [comment]
I'd be ok with this. Given that most of the code changes, improvements, that are in `base-x` came from `cryptocoinjs/bs58` over the years, my only request is that `base-x` is moved to `cryptocoinjs`.

**Comment by sublimator** [comment]
As an outsider to this bitter dispute, that seems fair to me haha :)

**Comment by sublimator** [comment]
Any further thought to this?

**Comment by sublimator** [comment]
:8ball: says ?

**Comment by dcousens** [comment]
@sublimator just a matter of priorities,  I haven't gotten around to this yet.

**Comment by sublimator** [comment]
Fair enough :)

**Comment by sublimator** [comment]
:+1:
