### ISSUE TITLE
decode_check

### ISSUE THREAD

**Issue by SterL** [cryptocoinjs/bs58#18]
I was informed that the base58 'decode' function is different from the 'decode_check' function. Is it possible for you to include the decode_check function as well?

**Comment by fanatid** [comment]
https://github.com/bitcoinjs/bs58check/ ?

**Comment by SterL** [comment]
Wow. That was a fast response. Thank you @fanatid !

**Comment by jprichardson** [comment]
Added a link to `bs58check` in the readme.
