### ISSUE TITLE
other base58 alphabets

### ISSUE THREAD

**Issue by fanatid** [cryptocoinjs/bs58#19]
[Ripple](https://wiki.ripple.com/Encodings) uses `rpshnaf39wBUDNEGHJKLM4PQRST7VWXYZ2bcdeCg65jkm8oFqi1tuvAxyz`
[Flickr](https://www.flickr.com/groups/api/discuss/72157616713786392/) uses `123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ`

*(bitcoin alphabet is `123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz`)*

We can put new alphabets to their own files (`require('bs58/ripple')` for example)

Thoughts?

**Comment by fanatid** [comment]
ping @flickr @ripple

**Comment by dcousens** [comment]
I think the use of `base-x` should alleviate this issue?
