### ISSUE TITLE
Uncaught TypeError: Expected Buffer

### ISSUE THREAD

**Issue by pundoo** [cryptocoinjs/bs58#41]
on api example, it says :

> input must be a Buffer or an Array

but gives error when running :

`bs58.encode(new Uint8Array([1, 2]));` or

`bs58.encode([1, 2])`;

bundled using browserify and running on chrome (latest version)

**Comment by junderw** [comment]
This was introduced in base-x@3.0.5 and was a breaking change from 3.0.4, so anyone that re-installed or re-packed would get errors if they didn't use Buffers.

https://github.com/cryptocoinjs/base-x/issues

**Comment by junderw** [comment]
Closing this issue for the other:

https://github.com/cryptocoinjs/base-x/issues/63
