### ISSUE TITLE
This library produces a different result from a different base58 converter library. Which is correct?

### ISSUE THREAD

**Issue by nickjuntilla** [cryptocoinjs/bs58#42]
This library's .decode function produces a hex code, which when converter to an integer does not match this library:

https://github.com/jimeh/node-base58#readme

Which library is producing the correct hex code?

**Comment by fanatid** [comment]
Can you provide code for reproducing? Thanks.

**Comment by nickjuntilla** [comment]
```
const bs58 = require('bs58');
const Base58 = require('base58');

// Creating Int with bs58 lib
const bytes = bs58.decode("9iS1fj");
const hex = bytes.toString('hex');
result1 =  parseInt(hex, 16);

// Creating Int with base58 lib
result2 = Base58.base58_to_int('9iS1fj'); 

// This is false
console.log(result1 === result2);


Base58.int_to_base58(6857269519); // 'brXijP'
Base58.base58_to_int('brXijP'); 
```

**Comment by fanatid** [comment]
`bs58` use bitcoin alphabet, while `base58` use Flickr alphabet.
In README: https://github.com/jimeh/node-base58#what
In code: https://github.com/cryptocoinjs/bs58/blob/master/index.js#L2 / https://github.com/jimeh/node-base58/blob/master/src/base58.js#L1
PR in `base58`: https://github.com/jimeh/node-base58/pull/10

**Comment by nickjuntilla** [comment]
@fanatid So it's just that the capital letters are reversed? Thank you for your quick response. I work with crypto so I will go with the bitcoin version. Thanks.
