### ISSUE TITLE
Invalid base58 characters

### ISSUE THREAD

**Issue by dmonza** [cryptocoinjs/bs58#45]
Hi,

I try it, but some bitcoin core adrresses include "l" and 0, such: 
tb1q8ecfmp2sa2s7nar3mdn7j7tyhehpu9npjylf5k
tb1qjh2gh5k57f4vkx6fuvan5y0stgshpxs2kmaqkv

Will be helpful to add an exception for it...

thanks,

**Comment by junderw** [comment]
Those are bech32 addresses. Not base58.

There are more than one type of encoding used in addresses.
