### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'decode')

### ISSUE THREAD

**Issue by AlexMGN** [cryptocoinjs/bs58#46]
Hello,

I'm looking to install the dependency on NestJS with yarn add bs58, in a rather classical way. It's the first time I use it with NestJS, and it turns out that I can't get access to bs58 functions. Is this normal? What can I do?

**Comment by junderw** [comment]
Please give steps to reproduce the error.

**Comment by AlexMGN** [comment]
I only yarn add bs58 on a NestJS API 😅 and after the import, I can see and check the decode method, but I cant use it

**Comment by junderw** [comment]
I just did that and it works fine.

Please give specific steps to reproduce the error, then reopen the issue.

Thanks.

**Comment by junderw** [comment]
This is what I did to try and reproduce the error. I was unsuccessful.
Please give specific steps on how to reproduce the error.

1. Create new nestjs app using Hello World example on their site. (`npm i -g @nestjs/cli` -> `nest new testbs58`)
2. Add `bs58` and `uint8array-tools` (`yarn add bs58` and `yarn add uint8array-tools`)
3. Change `app.service.ts`

```ts
import { Injectable } from '@nestjs/common';
import { compare } from 'uint8array-tools';
import * as bs58 from 'bs58';

@Injectable()
export class AppService {
  getHello(): string {
    const bytes = Uint8Array.from([234,123,46]);
    const text = '2Mm4Z';
    const text2 = bs58.encode(bytes);
    const bytes2 = bs58.decode(text);
    const results = [
      'Decode results: ' + (compare(bytes, bytes2) === 0 ? 'EQUAL' : 'NOT EQUAL'),
      'Encode results: ' + (text === text2 ? 'EQUAL' : 'NOT EQUAL'),
    ]
    return `Hello, World!<br>${results.join('<br>')}`
  }
}
```

4. Run the server and look at the page:

```
Hello, World!
Decode results: EQUAL
Encode results: EQUAL
```

**Comment by RohanKapurDEV** [comment]
I get the same issue. using `bs58.decode(SOME_TEXT)` on a NestJS project where i installed bs58 via `npm i bs58` results in the following error:

```bash
/Users/rohan/Desktop/code/test_project/src/main.ts:12
  console.log(bs58.decode(process.env.WALLET_PRIVATE_KEY));
                   ^
TypeError: Cannot read properties of undefined (reading 'decode')
    at bootstrap (/Users/rohan/Desktop/code/test_project/src/main.ts:12:20)
    at Object.<anonymous> (/Users/rohan/Desktop/code/test_project/src/main.ts:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
^C
```

**Comment by AlexMGN** [comment]
Hi ! In TypeScript we need to import bs58 differently. Import like this resolved my problem!

`import * as bs58 from 'bs58';`

**Comment by Gredys** [comment]
Such import doesn't work in Typescript.
`import * as bs58 from "bs58";`
It still says: `TS2339: Property encode does not exist on type`

**Comment by Gredys** [comment]
Correct import for TS: `import {default as bs58} from "bs58";`
